In [3]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [4]:
!python --version
print('NumPy', np.__version__)
print('Pandas', pd.__version__)
print('Matplotlib', mpl.__version__)

Python 3.13.5
NumPy 2.1.3
Pandas 2.2.3
Matplotlib 3.10.0

### Series

Es la unidad basica de datos de pandas, pude ser creada con una lista, tupla, diccionarios a rreglos de numpy

In [ ]:
# Una serie se crea con la funcion (pd.Series)
ciudades = ['Bogotá', 'Cali', 'Medellín','Barranquilla']
serie_ciudades = pd.Series(ciudades)
serie_ciudades

0          Bogotá
1            Cali
2        Medellín
3    Barranquilla
dtype: object

In [ ]:
# Validamos el timpo de dato de serie_inicial
type(serie_ciudades)

pandas.core.series.Series

In [9]:
# en una serie puedo definir tanto los indices como los valores
habitantes = (11344000,2228000,2569000,1206000)

#En este punto vamos a crear una serie con sus indices
serie_habitantes = pd.Series(
    data=habitantes,
    index= ciudades
)
serie_habitantes

Bogotá          11344000
Cali             2228000
Medellín         2569000
Barranquilla     1206000
dtype: int64

### Dataframe
Un data frame en la estructura de datos mas amplia y conocida de pandas, esta representa una tabla en donde cada columna representa una variable del estudio y cada fila o registro una medicion
El dataframe se compone de series y posee caracteristicas similares a la de una serie

In [10]:
datos = {
    'nombre_ciudad': ['Bogotá', 'Cali', 'Medellín','Barranquilla'],
    'poblacion' : (11344000,2228000,2569000,1206000),
    'altura' : np.array([2640,1018,1495,18])
}

# En este ejemplo el objeto de estudio son las ciudades
# Y cada columna es una variable con la que podemos describir a cada ciudad
ciudades = pd.DataFrame(datos)
ciudades

  nombre_ciudad  poblacion  altura
0        Bogotá   11344000    2640
1          Cali    2228000    1018
2      Medellín    2569000    1495
3  Barranquilla    1206000      18

### Ejemplo con dataframe housing

In [12]:
# Importamos la informacion de housing
housing = pd.read_csv("https://raw.githubusercontent.com/HarryVargas96/UdeCataluna/main/Housing.csv")

In [ ]:
# Obtenemos informacion sobre el dataframe
housing.shape

'''
Encontramos que el dataframe esta compuesto por 13 variables o columnas
y cuenta con 545 registros o mediciones
'''

(545, 13)

In [17]:
# Con esta propiedad (index) puedo consultar que indices componen el DF
housing.index

RangeIndex(start=0, stop=545, step=1)

In [ ]:
# consulto los valores (values) esta propiedad me permite ver los valores
#del DF como un arreglo de dos dimenciones
housing.values

array([[13300000, 7420, 4, ..., 2, 'yes', 'furnished'],
       [12250000, 8960, 4, ..., 3, 'no', 'furnished'],
       [12250000, 9960, 3, ..., 2, 'yes', 'semi-furnished'],
       ...,
       [1750000, 3620, 2, ..., 0, 'no', 'unfurnished'],
       [1750000, 2910, 3, ..., 0, 'no', 'furnished'],
       [1750000, 3850, 3, ..., 0, 'no', 'unfurnished']], dtype=object)

In [15]:
# Damos un vistaso a como se estructuran los datos con head
housing.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [ ]:
# Con tail puedo consultar las ultimas 5 filas del Df por defecto
housing.tail()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [ ]:
# El metodo .info() me muestra informacion detallada de las columnas que componen al DF
# me muestra un resumen de si contiene o no valores nulos
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB