In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
!python --version
print('NumPy', np.__version__)
print('Pandas', pd.__version__)
print('Matplotlib', mpl.__version__)

Python 3.13.5
NumPy 2.1.3
Pandas 2.2.3
Matplotlib 3.10.0

### Series

Es la unidad basica de datos de pandas, pude ser creada con una lista, tupla, diccionarios a rreglos de numpy

In [4]:
# Una serie se crea con la funcion (pd.Series)
ciudades = ['Bogotá', 'Cali', 'Medellín','Barranquilla']
serie_ciudades = pd.Series(ciudades)
serie_ciudades

0          Bogotá
1            Cali
2        Medellín
3    Barranquilla
dtype: object

In [5]:
# Validamos el timpo de dato de serie_inicial
type(serie_ciudades)

pandas.core.series.Series

In [6]:
# en una serie puedo definir tanto los indices como los valores
habitantes = (11344000,2228000,2569000,1206000)

#En este punto vamos a crear una serie con sus indices
serie_habitantes = pd.Series(
    data=habitantes,
    index= ciudades
)
serie_habitantes

Bogotá          11344000
Cali             2228000
Medellín         2569000
Barranquilla     1206000
dtype: int64

### Dataframe
Un data frame en la estructura de datos mas amplia y conocida de pandas, esta representa una tabla en donde cada columna representa una variable del estudio y cada fila o registro una medicion
El dataframe se compone de series y posee caracteristicas similares a la de una serie

In [7]:
datos = {
    'nombre_ciudad': ['Bogotá', 'Cali', 'Medellín','Barranquilla'],
    'poblacion' : (11344000,2228000,2569000,1206000),
    'altura' : np.array([2640,1018,1495,18])
}

# En este ejemplo el objeto de estudio son las ciudades
# Y cada columna es una variable con la que podemos describir a cada ciudad
ciudades = pd.DataFrame(datos)
ciudades

  nombre_ciudad  poblacion  altura
0        Bogotá   11344000    2640
1          Cali    2228000    1018
2      Medellín    2569000    1495
3  Barranquilla    1206000      18

### Ejemplo con dataframe housing

In [8]:
# Importamos la informacion de housing
housing = pd.read_csv("https://raw.githubusercontent.com/HarryVargas96/UdeCataluna/main/Housing.csv")

In [9]:
# Obtenemos informacion sobre el dataframe
housing.shape

'''
Encontramos que el dataframe esta compuesto por 13 variables o columnas
y cuenta con 545 registros o mediciones
'''

'\nEncontramos que el dataframe esta compuesto por 13 variables o columnas\ny cuenta con 545 registros o mediciones\n'

In [10]:
# Con esta propiedad (index) puedo consultar que indices componen el DF
housing.index

RangeIndex(start=0, stop=545, step=1)

In [11]:
# consulto los valores (values) esta propiedad me permite ver los valores
#del DF como un arreglo de dos dimenciones
housing.values

array([[13300000, 7420, 4, ..., 2, 'yes', 'furnished'],
       [12250000, 8960, 4, ..., 3, 'no', 'furnished'],
       [12250000, 9960, 3, ..., 2, 'yes', 'semi-furnished'],
       ...,
       [1750000, 3620, 2, ..., 0, 'no', 'unfurnished'],
       [1750000, 2910, 3, ..., 0, 'no', 'furnished'],
       [1750000, 3850, 3, ..., 0, 'no', 'unfurnished']], dtype=object)

In [12]:
# Damos un vistaso a como se estructuran los datos con head
housing.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [13]:
# Con tail puedo consultar las ultimas 5 filas del Df por defecto
housing.tail()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [14]:
# El metodo .info() me muestra informacion detallada de las columnas que componen al DF
# me muestra un resumen de si contiene o no valores nulos
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [15]:
# El metodo .describe() me ayuda a tener un resumen estadistico descriptivo
# del DF solo para valores cuantitativo es decir numeros
housing.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [16]:
# Si en housing quiero incluir los valores cualitativos o variables puedo
# agegar el paraemtro object, de esa forma podemos ver todas las variables categoricas
# o al incluir 'all' vemos todas las variables
housing.describe(include='all')

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545,545,545,545,545,545.000000,545,545
unique,NaN,NaN,NaN,NaN,NaN,2,2,2,2,2,NaN,2,3
top,NaN,NaN,NaN,NaN,NaN,yes,no,no,no,no,NaN,no,semi-furnished
freq,NaN,NaN,NaN,NaN,NaN,468,448,354,520,373,NaN,417,227
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,NaN,NaN,NaN,NaN,NaN,0.693578,NaN,NaN
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,NaN,NaN,NaN,NaN,NaN,0.861586,NaN,NaN
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,NaN,NaN,NaN,NaN,NaN,3.000000,NaN,NaN

In [17]:
housing.describe(include=object)

,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus
count,545,545,545,545,545,545,545
unique,2,2,2,2,2,2,3
top,yes,no,no,no,no,no,semi-furnished
freq,468,448,354,520,373,417,227

In [18]:
# puedo elegir solo una columna, para ahcer mas granular el estudio

precio = housing[['price']]
precio.head()

      price
0  13300000
1  12250000
2  12250000
3  12215000
4  11410000

In [19]:
# Existe un metodo que me permite tomar solo los datos de un tipo especifico
# .select_dtypes
# con esta funcion puedo tener todo el conjunto de datos de un tio de dato especifico listos para analizar


#housing.select_dtypes('number')
housing.select_dtypes('object')

,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus
0,yes,no,no,no,yes,yes,furnished
1,yes,no,no,no,yes,no,furnished
2,yes,no,yes,no,no,yes,semi-furnished
3,yes,no,yes,no,yes,yes,furnished
4,yes,yes,yes,no,yes,no,furnished
...,...,...,...,...,...,...,...
540,yes,no,yes,no,no,no,unfurnished
541,no,no,no,no,no,no,semi-furnished
542,yes,no,no,no,no,no,unfurnished
543,no,no,no,no,no,no,furnished
544,yes,no,no,no,no,no,unfurnished

In [20]:
housing.select_dtypes('number').mean()

price        4.766729e+06
area         5.150541e+03
bedrooms     2.965138e+00
bathrooms    1.286239e+00
stories      1.805505e+00
parking      6.935780e-01
dtype: float64

In [21]:
housing['price'].mean()

np.float64(4766729.247706422)

In [22]:
housing['price'].max()

13300000

In [23]:
housing['price'].min()

1750000

#### Analisis de variables categoricas o cualitativas

In [ ]:
# el metodo .unique() me muestra las valores unicos que conforman las mediciones de la variables
housing['furnishingstatus'].unique()

array(['furnished', 'semi-furnished', 'unfurnished'], dtype=object)

In [ ]:
# Con el metodo nunique() me permite regresar el numero de elementos unicos en la lista
housing['furnishingstatus'].nunique()

3

In [26]:
# el metodo value_counts() me permite tener un conteo de cada una de los valores en la variable
housing['furnishingstatus'].value_counts()

furnishingstatus
semi-furnished    227
unfurnished       178
furnished         140
Name: count, dtype: int64

In [28]:
# De esta forma puedo calcular el porcentaje de cada medida
numero_filas = housing.shape[0]

np.round(housing['furnishingstatus'].value_counts() / numero_filas*100 , 2)

furnishingstatus
semi-furnished    41.65
unfurnished       32.66
furnished         25.69
Name: count, dtype: float64